//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocDesignerEntities : DbContext
    {
        public DocDesignerEntities()
            : base("name=DocDesignerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BranchAction> BranchActions { get; set; }
        public virtual DbSet<BranchState> BranchStates { get; set; }
        public virtual DbSet<Commitment> Commitments { get; set; }
        public virtual DbSet<DocumentPrintLanguage> DocumentPrintLanguages { get; set; }
        public virtual DbSet<FragBranch> FragBranches { get; set; }
        public virtual DbSet<FragLock> FragLocks { get; set; }
        public virtual DbSet<Fragment> Fragments { get; set; }
        public virtual DbSet<FragmentCache> FragmentCaches { get; set; }
        public virtual DbSet<FragmentCacheItem> FragmentCacheItems { get; set; }
        public virtual DbSet<FragRef> FragRefs { get; set; }
        public virtual DbSet<FragReview> FragReviews { get; set; }
        public virtual DbSet<FragReviewInProgress> FragReviewInProgresses { get; set; }
        public virtual DbSet<FragState> FragStates { get; set; }
        public virtual DbSet<FragType> FragTypes { get; set; }
        public virtual DbSet<GROL> GROLs { get; set; }
        public virtual DbSet<GrolReleaseValidation> GrolReleaseValidations { get; set; }
        public virtual DbSet<GrolValidation> GrolValidations { get; set; }
        public virtual DbSet<HeadBranch> HeadBranches { get; set; }
        public virtual DbSet<License> Licenses { get; set; }
        public virtual DbSet<LPADocSuiteModule> LPADocSuiteModules { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<OutputFileType> OutputFileTypes { get; set; }
        public virtual DbSet<Role2LPADocSuiteModule> Role2LPADocSuiteModule { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<SpecValue> SpecValues { get; set; }
        public virtual DbSet<SpecValueTemplate> SpecValueTemplates { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<UserAccounts2License> UserAccounts2License { get; set; }
        public virtual DbSet<UserGroupCache> UserGroupCaches { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<WorkingBranch> WorkingBranches { get; set; }
    }
}
