//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FragBranch
    {
        public int BranchId { get; set; }
        public bool IsHead { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationComment { get; set; }
        public int CreationUserId { get; set; }
        public int FragId { get; set; }
        public byte[] Version { get; set; }
        public bool IsTranslated { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual Fragment Fragment { get; set; }
        public virtual HeadBranch HeadBranch { get; set; }
    }
}
