//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FragLock
    {
        public int Id { get; set; }
        public int BranchId { get; set; }
        public System.DateTime LockDate { get; set; }
        public bool ReadOnly { get; set; }
        public int LockUserId { get; set; }
        public Nullable<int> FragId { get; set; }
        public int EditFragId { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Fragment Fragment { get; set; }
        public virtual Fragment Fragment1 { get; set; }
        public virtual HeadBranch HeadBranch { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
