//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FragRef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FragRef()
        {
            this.GROLs = new HashSet<GROL>();
        }
    
        public int Position { get; set; }
        public string ChildName { get; set; }
        public string ChildAlias { get; set; }
        public string DisplayExpression { get; set; }
        public string BookMark { get; set; }
        public string TargetFrame { get; set; }
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Fragment Fragment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROL> GROLs { get; set; }
    }
}
