//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FragmentCache
    {
        public int Id { get; set; }
        public byte[] FragHash { get; set; }
        public string FragName { get; set; }
        public string Lang { get; set; }
        public string Culture { get; set; }
        public string BankGroup { get; set; }
        public string Bank { get; set; }
        public string UserGroup { get; set; }
        public string Layout { get; set; }
        public string Modul { get; set; }
        public string ProdGroup { get; set; }
        public string ProdSubGroup { get; set; }
        public string Product { get; set; }
        public string CustomerOp { get; set; }
        public string Condition1 { get; set; }
        public string Condition2 { get; set; }
        public string Condition3 { get; set; }
        public string Condition4 { get; set; }
        public string Condition5 { get; set; }
        public string Condition6 { get; set; }
        public string Condition7 { get; set; }
        public string AppContext { get; set; }
    }
}
