//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrolValidation
    {
        public int Id { get; set; }
        public int GrolId { get; set; }
        public Nullable<int> MaxPageCount { get; set; }
        public byte[] Version { get; set; }
    
        public virtual GROL GROL { get; set; }
    }
}
