//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrolReleaseValidation
    {
        public int Id { get; set; }
        public int GrolId { get; set; }
        public int ProductId { get; set; }
        public int BranchId { get; set; }
        public string Cond0 { get; set; }
        public string Cond1 { get; set; }
        public string Cond2 { get; set; }
        public string Cond3 { get; set; }
        public string Cond4 { get; set; }
        public string Cond5 { get; set; }
        public string Cond6 { get; set; }
        public string Cond7 { get; set; }
        public int BranchCounter { get; set; }
        public Nullable<int> ValidationBranchId { get; set; }
        public Nullable<int> ValidationUserId { get; set; }
        public Nullable<System.DateTime> ValidationDate { get; set; }
        public bool IsValid { get; set; }
        public byte[] Version { get; set; }
    
        public virtual GROL GROL { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual WorkingBranch WorkingBranch { get; set; }
    }
}
