//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROL()
        {
            this.GrolReleaseValidations = new HashSet<GrolReleaseValidation>();
            this.GrolValidations = new HashSet<GrolValidation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> RootDocId { get; set; }
        public byte OutputFileTypeId { get; set; }
        public int LanguageId { get; set; }
        public byte[] Version { get; set; }
        public string StaticDocName { get; set; }
        public string Country { get; set; }
        public string AppContext { get; set; }
        public string BankGroup { get; set; }
        public string Bank { get; set; }
        public string UserGroup { get; set; }
        public string Layout { get; set; }
        public string CultureFormatName { get; set; }
    
        public virtual DocumentPrintLanguage DocumentPrintLanguage { get; set; }
        public virtual FragRef FragRef { get; set; }
        public virtual OutputFileType OutputFileType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrolReleaseValidation> GrolReleaseValidations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrolValidation> GrolValidations { get; set; }
    }
}
