//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreationUserId { get; set; }
        public bool IsPublished { get; set; }
        public byte[] WordContent { get; set; }
        public byte[] HtmlContent { get; set; }
        public byte[] Version { get; set; }
        public int LanguageId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
