//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specialization()
        {
            this.Specialization1 = new HashSet<Specialization>();
            this.SpecValues = new HashSet<SpecValue>();
            this.SpecValueTemplates = new HashSet<SpecValueTemplate>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string SpecName { get; set; }
        public string GuiName { get; set; }
        public int Priority { get; set; }
        public bool Visible { get; set; }
        public Nullable<bool> UniqueParent { get; set; }
        public string Hint { get; set; }
        public string de { get; set; }
        public byte[] Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialization> Specialization1 { get; set; }
        public virtual Specialization Specialization2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecValue> SpecValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecValueTemplate> SpecValueTemplates { get; set; }
    }
}
