//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecValueTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecValueTemplate()
        {
            this.SpecValueTemplate1 = new HashSet<SpecValueTemplate>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int SpecializationId { get; set; }
        public string SpecValue { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Specialization Specialization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecValueTemplate> SpecValueTemplate1 { get; set; }
        public virtual SpecValueTemplate SpecValueTemplate2 { get; set; }
    }
}
