//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecValue()
        {
            this.SpecValue11 = new HashSet<SpecValue>();
        }
    
        public int Id { get; set; }
        public int BranchId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int SpecializationId { get; set; }
        public string SpecValue1 { get; set; }
        public string de { get; set; }
        public string en { get; set; }
        public string es { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Specialization Specialization { get; set; }
        public virtual WorkingBranch WorkingBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecValue> SpecValue11 { get; set; }
        public virtual SpecValue SpecValue2 { get; set; }
    }
}
