//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccounts2License
    {
        public int Id { get; set; }
        public int LicenseId { get; set; }
        public int UserAccountsId { get; set; }
        public bool Used { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual License License { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
