//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupCache
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string GroupSID { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
