//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAppDomain.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingBranch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkingBranch()
        {
            this.GrolReleaseValidations = new HashSet<GrolReleaseValidation>();
            this.SpecValues = new HashSet<SpecValue>();
            this.UserAccounts = new HashSet<UserAccount>();
            this.WorkingBranch1 = new HashSet<WorkingBranch>();
        }
    
        public int Id { get; set; }
        public byte BranchStateId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SourceId { get; set; }
        public bool IsClosed { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationComment { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public string DeletionComment { get; set; }
        public int CreationUserId { get; set; }
        public Nullable<int> DeletionUserId { get; set; }
        public byte[] Version { get; set; }
        public bool IsHead { get; set; }
        public int HeadBranchId { get; set; }
        public byte BranchActionId { get; set; }
        public Nullable<int> MergedBranchId { get; set; }
    
        public virtual BranchAction BranchAction { get; set; }
        public virtual BranchState BranchState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrolReleaseValidation> GrolReleaseValidations { get; set; }
        public virtual HeadBranch HeadBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecValue> SpecValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAccount UserAccount1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingBranch> WorkingBranch1 { get; set; }
        public virtual WorkingBranch WorkingBranch2 { get; set; }
    }
}
